import { StyleSheet } from 'react-native';

/** Matches web `AcademicsView` gradient + glass panels. */
export const AcademicsColors = {
  gradient: ['#8b0000', '#A80532', '#c0182a', '#6b0f2a'] as const,
  white: '#ffffff',
  white70: 'rgba(255,255,255,0.70)',
  white50: 'rgba(255,255,255,0.50)',
  white25: 'rgba(255,255,255,0.25)',
  white12: 'rgba(255,255,255,0.12)',
  white08: 'rgba(255,255,255,0.08)',
  darkGlass: 'rgba(0,0,0,0.22)',
  primary: '#A80532',
  textDark: '#1a1a2e',
} as const;

export const academicsStyles = StyleSheet.create({
  flex1: { flex: 1 },
  topBarRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
  },
  dashboardBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: AcademicsColors.white25,
    backgroundColor: AcademicsColors.white08,
  },
  dashboardBtnText: {
    color: 'rgba(255,255,255,0.88)',
    fontWeight: '700',
    fontSize: 12,
    marginLeft: 4,
  },
  containerPad: {
    paddingHorizontal: 16,
    paddingBottom: 100,
    paddingTop: 4,
  },
  glassPanel: {
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    backgroundColor: AcademicsColors.darkGlass,
    borderWidth: 1,
    borderColor: AcademicsColors.white12,
  },
  lightPanel: {
    borderRadius: 16,
    padding: 14,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  label: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 11,
    marginBottom: 4,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: AcademicsColors.white12,
    backgroundColor: AcademicsColors.white08,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#fff',
    fontSize: 13,
    minWidth: 72,
  },
  inputMultiline: {
    minHeight: 36,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'flex-end',
  },
  primaryBtn: {
    backgroundColor: AcademicsColors.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  primaryBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 12,
  },
  ghostBtn: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.40)',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  ghostBtnText: {
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '800',
    fontSize: 12,
  },
  searchInput: {
    flex: 1,
    minWidth: 200,
    maxWidth: 400,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: AcademicsColors.white12,
    backgroundColor: 'rgba(0,0,0,0.20)',
    paddingHorizontal: 14,
    paddingVertical: 9,
    color: '#fff',
    fontSize: 13,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  chipText: {
    fontSize: 11,
    fontWeight: '800',
  },
  emptyCard: {
    borderRadius: 16,
    padding: 22,
    alignItems: 'center',
    backgroundColor: AcademicsColors.white08,
    borderWidth: 1,
    borderColor: AcademicsColors.white12,
  },
  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 88,
    padding: 14,
    borderRadius: 14,
    zIndex: 50,
  },
  toastText: { color: '#fff', fontWeight: '700', fontSize: 14 },
});
