import { StyleSheet } from 'react-native';

import { Brand } from '@/constants/brand';

export const marketplaceScreenStyles = StyleSheet.create({
  /** Counteracts FeatureScreenShell horizontal padding for full-bleed sections */
  bleed: {
    marginHorizontal: -16,
  },

  heroGradient: {
    paddingBottom: 24,
    paddingTop: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.15)',
  },
  heroInner: {
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.95)',
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 18,
  },
  sellBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 999,
    marginBottom: 22,
  },
  sellBtnText: {
    color: Brand.primary,
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.5,
  },

  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    fontSize: 16,
    color: '#1F2937',
    fontWeight: '500',
  },
  searchSubmit: {
    backgroundColor: Brand.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  searchSubmitText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
    letterSpacing: 0.5,
  },

  categoryStrip: {
    paddingVertical: 14,
    paddingLeft: 16,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255,255,255,0.2)',
  },
  categoryChip: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    marginRight: 10,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.4)',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  categoryChipActive: {
    backgroundColor: '#fff',
    borderColor: '#fff',
  },
  categoryChipText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
    letterSpacing: 0.3,
  },
  categoryChipTextActive: {
    color: Brand.primary,
  },

  resultsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexWrap: 'wrap',
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.15)',
  },
  resultsCount: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  resultsCountNum: {
    fontSize: 20,
    fontWeight: '800',
  },
  sortScroll: { maxHeight: 40 },
  sortChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.95)',
    marginRight: 8,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  sortChipActive: {
    borderColor: '#fff',
  },
  sortChipText: {
    color: Brand.primary,
    fontWeight: '700',
    fontSize: 13,
  },

  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 8,
  },

  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  cardImageWrap: {
    height: 160,
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  conditionBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    zIndex: 2,
  },
  conditionBadgeText: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
    borderWidth: 2,
  },
  textbookBadge: {
    position: 'absolute',
    left: 12,
    zIndex: 2,
  },
  textbookBadgeText: {
    backgroundColor: Brand.primary,
    color: '#fff',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  favBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  cardBody: {
    padding: 14,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 6,
  },
  cardDesc: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
    marginBottom: 10,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  priceMain: {
    fontSize: 22,
    fontWeight: '800',
    color: Brand.primary,
  },
  priceStrike: {
    fontSize: 15,
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  savePill: {
    alignSelf: 'flex-start',
    backgroundColor: '#DCFCE7',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 4,
    marginBottom: 10,
  },
  savePillText: {
    color: '#16A34A',
    fontSize: 12,
    fontWeight: '700',
  },
  sellerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 12,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  sellerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  sellerMeta: { flex: 1, minWidth: 0 },
  sellerName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  sellerLoc: {
    fontSize: 12,
    color: '#6B7280',
  },
  contactBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Brand.primary,
    paddingVertical: 12,
    borderRadius: 8,
  },
  contactBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  postedAt: {
    marginTop: 10,
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
  },

  centerState: {
    paddingVertical: 48,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  stateText: {
    marginTop: 12,
    fontSize: 15,
    color: '#6B7280',
    fontWeight: '500',
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: 16,
    backgroundColor: Brand.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  retryBtnText: {
    color: '#fff',
    fontWeight: '700',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(168, 5, 50, 0.75)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 22,
    borderWidth: 2,
    borderColor: 'rgba(168, 5, 50, 0.15)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: Brand.primary,
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  modalClose: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(168, 5, 50, 0.1)',
    borderWidth: 2,
    borderColor: 'rgba(168, 5, 50, 0.2)',
  },
  modalPreview: {
    flexDirection: 'row',
    gap: 14,
    backgroundColor: 'rgba(168, 5, 50, 0.05)',
    padding: 14,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(168, 5, 50, 0.1)',
  },
  modalThumb: {
    width: 72,
    height: 72,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(168, 5, 50, 0.2)',
  },
  modalItemTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 6,
  },
  modalItemPrice: {
    fontSize: 20,
    fontWeight: '800',
    color: Brand.primary,
  },
  modalInput: {
    borderWidth: 2,
    borderColor: 'rgba(168, 5, 50, 0.2)',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    minHeight: 120,
    textAlignVertical: 'top',
    marginBottom: 16,
    color: '#111',
  },
  modalSend: {
    backgroundColor: Brand.primary,
    paddingVertical: 14,
    borderRadius: 999,
    alignItems: 'center',
  },
  modalSendDisabled: {
    backgroundColor: '#9CA3AF',
  },
  modalSendText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
    letterSpacing: 0.5,
  },

  favSlot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  favSlotText: {
    fontSize: 13,
    fontWeight: '800',
    color: Brand.primary,
    maxWidth: 36,
  },
});
